# set(CMAKE_GENERATOR "Unix Makefiles" CACHE INTERNAL "")
set(CMAKE_GENERATOR "Ninja" CACHE INTERNAL "")
set(CMAKE_C_COMPILER "clang" CACHE INTERNAL "")
set(CMAKE_CXX_COMPILER "clang++" CACHE INTERNAL "")